name: baseline_sketch
channels:
  - pytorch
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py310h5f69134_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - assimp=5.4.3=h31c7375_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py310h1af2607_4
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8e7cc95_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cpuonly=2.0=0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dash=3.2.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - double-conversion=3.3.1=h286801f_0
  - eigen=3.4.0=h1995070_0
  - embree=4.4.0=h3a6d975_0
  - expat=2.7.1=hec049ff_0
  - ffmpeg=7.1.1=gpl_hcf420f2_109
  - filelock=3.19.1=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - fmt=11.2.0=h440487c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py310h5f69134_0
  - freeimage=3.18.0=h2e169f6_22
  - freetype=2.13.3=hce30654_1
  - fribidi=1.0.10=h27ca646_0
  - frozenlist=1.7.0=py310ha18c8e3_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=h7af3d76_3
  - geos=3.13.1=hc9a1286_0
  - giflib=5.2.2=h93a5062_0
  - glew=2.1.0=h9f76cd9_2
  - glfw=3.5.0=h6caf38d_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h8086d47_1
  - graphite2=1.3.14=hec049ff_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.4.5=hf4e55d4_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_he65715a_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.1.12=h025cafa_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jasper=4.2.8=hc0e5025_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsoncpp=1.9.6=h726d253_1
  - jxrlib=1.1=h93a5062_3
  - kaldi=5.5.1172=cpu_h0f61937_1
  - kiwisolver=1.4.9=py310h92dc006_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=35_h10e41b3_openblas
  - libboost=1.88.0=h18cd856_3
  - libboost-devel=1.88.0=hf450f58_3
  - libboost-headers=1.88.0=hce30654_3
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=35_hb3479ef_openblas
  - libclang-cpp19.1=19.1.7=default_hf90f093_3
  - libclang13=21.1.0=default_h91d7d2a_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=21.1.0=hf598326_1
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=15.1.0=hfdf1602_1
  - libgfortran5=15.1.0=hb74de2c_1
  - libglib=2.84.3=h587fa63_0
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=35_hc9a63f6_openblas
  - liblapacke=3.9.0=35_hbb7bcf8_openblas
  - libllvm19=19.1.7=hc4b4ae8_1
  - libllvm21=21.1.0=h846d351_0
  - liblzf=3.6=hd74edd7_3
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnetcdf=4.9.2=nompi_h2d3d5cf_118
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=pthreads_hc7ce18b_2
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libpq=17.6=h6846fd6_1
  - libprotobuf=6.31.1=h702a38d_1
  - libraw=0.21.4=h62a31ad_0
  - librsvg=2.58.4=h266df6f_3
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.7.0=h025e3ab_6
  - libtorch=2.7.1=cpu_generic_h8557a0d_4
  - libusb=1.0.29=hbc156a2_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libwebp=1.6.0=hc0253d1_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h4a9ca0c_1
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.0=hbb9b287_0
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.2=py310hc74094e_1
  - matplotlib=3.10.6=py310hb6292c7_1
  - matplotlib-base=3.10.6=py310h0181960_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py310hc9b05e5_1
  - multidict=6.6.3=py310hdf261b0_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.3.0=pyhcf101f3_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=ha1acc90_0
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.2.6=py310h4d83441_0
  - occt=7.9.0=all_h749081a_204
  - open3d=0.19.0=py310hfa88921_4
  - openexr=3.3.5=haaeed0a_0
  - openfst=1.8.4=ha393de7_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.3=h889cd5d_1
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.5.2=he92f556_0
  - optree=0.17.0=py310hc9b05e5_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py310h03dc5a2_0
  - pango=1.56.4=h875632e_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=ha881caa_0
  - pillow=11.3.0=py310h45d6349_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - plotly=6.3.0=pyhd8ed1ab_0
  - proj=9.6.2=hdbeaa80_2
  - propcache=0.3.1=py310hc74094e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyrr=0.10.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=h6cefb37_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pythonocc-core=7.9.0=all_h9352948_200
  - pytorch=2.7.1=cpu_generic_py310_h20f5f40_4
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310hc74094e_2
  - qhull=2020.2=h420ef59_5
  - qt6-main=6.9.2=hd1b78a2_0
  - rapidjson=1.1.0.post20240409=ha1acc90_2
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - retrying=1.4.2=pyhe01879c_0
  - scipy=1.15.2=py310h32ab4ed_0
  - sdl2=2.32.54=ha1acc90_0
  - sdl3=3.2.22=he22eeb8_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.1=py310h5d48654_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hd121638_0
  - sqlite=3.50.4=hb5dd463_0
  - statsmodels=0.14.5=py310h307809b_0
  - svgwrite=1.4.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.2.0=h5b2e6d4_1
  - tbb-devel=2022.2.0=h89693d0_1
  - tinyobjloader=1.0.7=hebf3989_2
  - tk=8.6.13=h892fb3f_2
  - torchaudio=2.8.0=cpu_py310hfaa5709_0
  - torchcodec=0.6.0=cpu_py310_h99e2500_1
  - torchvision=0.22.0=cpu_py310_hfba4689_2
  - torchvision-extra-decoders=0.0.2=py310h74cdeaf_3
  - tornado=6.5.2=py310h7bdd564_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h7bdd564_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utfcpp=4.0.6=h54c0426_0
  - vtk-base=9.4.2=py310he2a5707_3
  - vtk-io-ffmpeg=9.4.2=h6060850_3
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wslink=2.4.0=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.20.1=py310hc74094e_0
  - zeromq=4.3.5=hc0cf3cd_8
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.24.0=py310h13cc3cc_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - addict==2.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - anytree==2.13.0
      - asttokens==3.0.0
      - build123d==0.9.0
      - cachetools==6.2.1
      - cadquery-ocp==7.8.1.1.post1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - ezdxf==1.4.2
      - fastapi==0.119.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.186.0
      - google-auth==2.42.1
      - google-auth-httplib2==0.2.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - iopath==0.1.10
      - ipython==8.37.0
      - jedi==0.19.2
      - jiter==0.11.0
      - matplotlib-inline==0.1.7
      - numpy-stl==3.2.0
      - ocpsvg==0.5.0
      - omegaconf==2.3.0
      - openai==1.109.1
      - opencv-python==4.12.0.88
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-lib3mf==2.3.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.10
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - python-utils==3.9.1
      - regex==2025.10.23
      - rsa==4.9.1
      - safetensors==0.6.2
      - sam-2==1.0
      - segment-anything==1.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.48.0
      - supervision==0.26.1
      - svgelements==1.9.6
      - svgpathtools==1.7.1
      - timm==1.0.21
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch-geometric==2.6.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - trianglesolver==1.2
      - trimesh==4.8.2
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - uvicorn==0.37.0
      - vtk==9.3.1
      - wcwidth==0.2.13
      - yapf==0.43.0
prefix: /Users/yuanboli/miniforge3/envs/baseline_sketch
